### ISSUE TITLE
Snap location selection to grid

### ISSUE THREAD

**Issue by aaron-kaplan** [iridl/python-maprooms#144]
Subseasonal forecast maproom and fbfmaproom both snap position to grid. Do the same for onset maproom.

**Comment by remicousin** [comment]
I will work on that now and possibly remove the type-in box labels.

**Comment by remicousin** [comment]
On 2nd thought, I don't think I want to have multiple PRs on same project-ish. So will wait for my open PR to merge

**Comment by remicousin** [comment]
Will do once the pick location callbacks are all set.

**Comment by remicousin** [comment]
PR #205 resolves this
