### ISSUE TITLE
Confusion about Ingrid colormap representation

### ISSUE THREAD

**Issue by remicousin** [iridl/python-maprooms#146]
> Turns out that out of the 4 cases I ran into: fbf's Ingrid colormap's representation; correlationcolorscale and the 2 PoE colorscales (once static); only the fbf's one has Ingrid's colormap returns something that corresponds to what start/endcolormap states. In the 3 other cases, colors order were switched, and/or replaced, and/or additional incrementations/sequencing were added...

I didn't understand this. If you want me to help look into it, please provide more details. I think we can merge this in the meantime.

_Originally posted by @aaron-kaplan in https://github.com/iridl/python-maprooms/issues/113#issuecomment-1194425554_

**Comment by remicousin** [comment]
Ingrid's colormap is not doing what we expect. Worst case scenario I found:
correlationcolorscale, defined in [Ingrid](https://bitbucket.org/iridl/ingrid/src/master/src/ingridinit.tex#lines-17290) returns a [colormap](http://iridl.ldeo.columbia.edu/SOURCES/.NOAA/.NCEP-NCAR/.CDAS-1/.MONTHLY/.Intrinsic/.PressureLevel/.phi/correlationcolorscale/colormap/#expert) where:

- colors' order are reverted (reds first then blues, e.g. first color 8388608 is [Dark Red](https://www.mathsisfun.com/hexadecimal-decimal-colors.html)
- Neutral color 11920639 is not Ingrid's mocassin and 13959039 is not Ingrid's aquamarine

Interestingly enough, Ingrid's aquamarine is
/aquamarine     127 255 212     RGBdef
but  13959039 [returns](https://www.mathsisfun.com/hexadecimal-decimal-colors.html) RGB 212 255 127 

As far as I can tell, pingrid.py returns what colormap is, which is not the Ingrid colorscale. So can't blame pingrid.py... but can't rely on Ingrid's colormap, thus can't reallt use pingrid.py features that rely on it.

I ran into other similar cases. The Ingrid colormap in fbfmaproom config file is reproducing what it's supposed to.

**Comment by aaron-kaplan** [comment]
You've discovered that Ingrid's single-integer color representation puts blue in the most significant bits, then green, then red in the least significant bits. This is confirmed by the Ingrid definition of [RGB](https://bitbucket.org/iridl/ingrid/src/9561370dc1517975c45aa3c6a21a2720fd331ed4/src/ingridinit.tex#lines-10671:10677) and by the definition of parse_color in pingrid.py. The converter on mathisfun.com uses the opposite order, so isn't helpful here.

I'm not sure that explains everything you said. If not, provide more details about e.g. additional incrementations.

**Comment by remicousin** [comment]
mathisfun might not help but in the app, when using the output of colormap, I got what mathisfun says. That is for correlationcolorscale: shades of dark to light red, then some sort of blue-grey color, then shades of light blue to dark blue. 

As for what I meant about "additional incrementations," looking back at what I was thinking, I take back what I said. But still the output of colormap, once fed into pingrid.py utilities, didn't return the same color scale.

**Comment by aaron-kaplan** [comment]
Ahh..... that must be what [this](https://github.com/iridl/python-maprooms/commit/b5acaaf2b0047d95b535b4f876b2c6bb2e9c2a74) was for! Igor must have run into this and coded around it, but by the time I got to it we were no longer using a colorscale that required it, so I couldn't figure out why it was there.

Does that explain everything, or are there still colors that don't match?


I imagine we could figure out why some colorsmaps are reversed and some aren't if we dove into the ingrid code, but if it's easy to work around, it might not be worth it.

**Comment by remicousin** [comment]
It seems so. I get correlationcolorscale in the right order, But still one or maybe 2 wrong individual colors. Not sure my test is a full reverse as your changed are in maproom.py while I am playing here with pingrid.py.
Maybe there are other differences in pingrid since then that makes comparison diffcult, or maybe I am not using the right color scales functions in the right places, or a bit of both.
I'll have to look into it further.

**Comment by remicousin** [comment]
Note to myself: I need to look at DataArrayEntry to get to the bottom (some bottom) of things

**Comment by remicousin** [comment]
I was suspecting there was some business going on with the bands order. I'll give it a look.

**Comment by remicousin** [comment]
I made another dummy change in #165 that does the right thing for my case study (printing/applying Ingrid correlationcolorscale - case "Precipitation Anomaly" in the forecast maproom). Note the flip of colors is not applied anymore.

See if that makes sense to you. Then I am a bit worried of the intrications of this maze, plus you are working on pingrid now. So let me know if you want to take over or give me some directions.

**Comment by remicousin** [comment]
Resolved through PR #244
