### ISSUE TITLE
Flexible forecast Maproom offers controls to select S/L

### ISSUE THREAD

**Issue by remicousin** [iridl/python-maprooms#150]
The subseasonal version of this Maproom has been merged to master. At present, I don't think there is anything in it that makes it specific to subseasonal (would work same way as for seasonal), except the datafiles reading and the retrieval and printing of S, L, target date in the app.

The next step is to have the app offer more than one S/L to viz'. The sample config file points to a folder where there is a set of S/Ls and can be used to try and set that up. Even though we don't have a sample of files for seasonal forecasts, setting up the subseasonal case should be done trying to be ready to work as well for the seasonal one.

**Comment by drewmresnick** [comment]
Just for clarification: this issue is referring to the maproom built [here](https://github.com/iridl/python-maprooms/tree/master/subseas_flex_fcst)?

**Comment by remicousin** [comment]
yes

**Comment by remicousin** [comment]
Controls exist since this [PR](https://github.com/iridl/python-maprooms/pull/156), even if work is ongoing to better those controls as I close this.
