### ISSUE TITLE
convert loading / sorting start dates code to function

### ISSUE THREAD

**Issue by drewmresnick** [iridl/python-maprooms#173]
This will probably help to convert to a function as well, so we can modulate when wanting to use this for other kind of forecasts. Can make that an issue for now.

_Originally posted by @remicousin in https://github.com/iridl/python-maprooms/pull/156#discussion_r974670451_

**Comment by remicousin** [comment]
This and issue #174 would probably benefit from trying and apply to seasonal CPT outputs. We need some sample files that hopefully we can find from AICCRA colleagues to play with.

**Comment by drewmresnick** [comment]
@remicousin I actually just [opened a PR](https://github.com/iridl/python-maprooms/pull/187) that does a first attempt at making a function out of this code. Did not see that we had already made an issue for this as well. I will make you a reviewer, if you have any thoughts on this. I also thought about addressing issue #174 in the same PR but did not know if I should hold off working on that one.

**Comment by remicousin** [comment]
That's fine. There is factoring functions and then there is making them work for other cases. I just thought it would be more straightforward to do both together, when we have an example to run against.

**Comment by drewmresnick** [comment]
Sure, I figure it does not matter much to just move them for now, and then when we get data to play around with for an additional example we could do that separately? I assume there might be some other fixes we may have to make to the code overall to accommodate different data that we might not be thinking of just yet.
