### ISSUE TITLE
Print all boundary info on hover & click for onset maproom

### ISSUE THREAD

**Issue by drewmresnick** [iridl/python-maprooms#176]
I'd think we should be able to accommodate both independently. Checkboxes to control the different layers of admin on one hand. On the other hand, infer name of the of the smallest level admin the mouse is hovering, even if that level is not a currently checked layer. In almost all admin databases, they contain the name of the geometries and the names of the higher levels they belong, so one can get the full information by querying the smallest admin level and print e.g. name3, name2, name1. There will be cases when name2, name1 are not there... We'll have to deal with these as exceptions somehow.

(The piece of code generating that will likely be reusable for the other item Aaron was mentioning: print that same information along with the graphs when clicking a  gridbox, as Ingrid/uicore does.)

As to where to print the information when mousing over... I don't know. I agree that it's not great to obstruct the map with a pop-up. On the other hand, since it's meant to help figuring out where to click, it's convenient that it would be by the mouse... Maybe the bottom right corner of the map (by the "Leaflet" mark)? or right above or right below the map?

Sorry I feel like we are often make you redo things a good deal. Maybe we should have brief discussions before starting projects... On the other hand, doing something and then change to something else means more things done, thus more learning...

_Originally posted by @remicousin in https://github.com/iridl/python-maprooms/issues/171#issuecomment-1253753756_

**Comment by drewmresnick** [comment]
Refer to [previous commits](https://github.com/iridl/python-maprooms/pull/171/commits/e61a6206a4fa6d12f80cd789393c118916f4c437) for inspiration on how to make a callback for hovering over boundary and getting info returned

**Comment by remicousin** [comment]
Looking to print the name of the finest admin boundary level name that is being moused hover, somewhere below the map maybe, it seems hover_feature would be the most straightforward property to use. However, now that that admin layers are within a callback to be set, I run into the same problem that I can't use their IDs as inputs.

So I am looking into whether there is something like hover_lat_lng to create a callback that would use that to find the name of the geometry that lat/lng is in, but there doesn't seem to be such a thing.

So maybe the way we initialize maps needs to be fixed before this could move forward? Or I am missing out something... In the past weeks, I realized I struggle quite a bit to find Dash Leaflet documentation or examples...

**Comment by aaron-kaplan** [comment]
You can use a [pattern-matching callback](https://dash.plotly.com/pattern-matching-callbacks) to attach a callback to a component that gets added dynamically.

**Comment by remicousin** [comment]
Resolved by PR #195
