### ISSUE TITLE
Bug in set_colorbar callback

### ISSUE THREAD

**Issue by drewmresnick** [iridl/python-maprooms#201]
When option selected is 'pe' there is the error

`AttributeError: module 'pingrid' has no attribute 'CORRELATION_COLORMAP_KEY'`

Editing the key to match the pingrid file var which is, `'CORRELATION_COLORMAP` then throws:

`TypeError: to_dash_colorscale() got an unexpected keyword argument 'thresholds'`

I have not finished debugging since I found this while working on something else, so I put it in this issue for now and will open a separate PR with the fix.

**Comment by drewmresnick** [comment]
@remicousin I found a bug in the onset maproom when you select "pe" from the map display options, in trying to print the colorbar. So I will fix it in a new PR unless you already know something about it.

**Comment by remicousin** [comment]
yes, it's being addressed in an ongoing PR. Thanks!

**Comment by drewmresnick** [comment]
Okay great

**Comment by remicousin** [comment]
resolved through PR #244
