### ISSUE TITLE
Unifying widgets

### ISSUE THREAD

**Issue by drewmresnick** [iridl/python-maprooms#208]
Make sure that all widgets.py files are in sync with the new changes being made to the lms-monthly and onset maprooms. 

Includes renaming of the file and some functions, adding new parameters within functions. 

Also removing ison parameter from Block() to follow [comment made my Aaron](https://github.com/iridl/lms-monthly/pull/1#discussion_r998522689):

"I see. [Here's](https://github.com/iridl/python-maprooms/blob/c43d63d155e683280b1c83679ead80c9d00a537c/onset_maproom/layout.py#L331) where that's used. I think we should conditionally include/exclude the Block from the list in that case, instead of always including it but sometimes hiding it. (That requires a PR in the python-maprooms repo). And then remove the ison parameter from Block."

**Comment by remicousin** [comment]
Resolved by PR #247
