### ISSUE TITLE
Add 6-band colorscale to crop suitability maproom

### ISSUE THREAD

**Issue by drewmresnick** [iridl/python-maprooms#358]
give this guy a nice 6-band colorscale since we can do that now? Can be in this PR or an issue.

_Originally posted by @remicousin in https://github.com/iridl/python-maprooms/pull/280#discussion_r1189982907_

**Comment by remicousin** [comment]
and precip and temp colorscales for the other maps.

**Comment by remicousin** [comment]
Resolved by PR #367
